openapi: 3.0.0
info:
  title: linked_clone_api
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: backend server

paths:
  /posts:
    get:
      tags:
        - posts
      summary: Get all posts
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/posts"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      tags:
        - posts
      summary: Create a new posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/posts"
      responses:
        "201":
          description: posts created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/posts"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      tags:
        - "posts"
      summary: Update a posts by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/posts"
      responses:
        "200":
          description: posts updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/posts"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      tags:
        - "posts"
      summary: Delete a posts by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: posts deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /auth/login:
    post:
      tags:
        - "auth"
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
                      username:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
                      image:
                        type: string
                      headline:
                        type: string
                      summary:
                        type: string
                      email:
                        type: string
                      # time_stamp:
                      #   type: string
                      education:
                        type: array
                        items:
                          type: object
                        properties:
                          school:
                            type: string
                          degree:
                            type: string
                          field_of_study:
                            type: string
                          start_date:
                            type: string
                          end_date:
                            type: string
                          description:
                            type: string
                      skill:
                        type: array
                        items:
                          type: object
                        properties:
                          skill:
                            type: string
                          time_stamp:
                            type: string
                      experience:
                        type: array
                        items:
                          type: object
                        properties:
                          title:
                            type: string
                          company:
                            type: string
                          start_date:
                            type: string
                          end_date:
                            type: string
                          description:
                            type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid username or password"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request / Data missing"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
  /auth/register:
    post:
      tags:
        - "auth"
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  username:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string
                  image:
                    type: string
                  headline:
                    type: string
                  summary:
                    type: string
                  email:
                    type: string
                  # time_stamp:
                  #   type: string
                  education:
                    type: array
                    items:
                      type: object
                    properties:
                      school:
                        type: string
                      degree:
                        type: string
                      field_of_study:
                        type: string
                      start_date:
                        type: string
                      end_date:
                        type: string
                      description:
                        type: string
                  skill:
                    type: array
                    items:
                      type: object
                    properties:
                      skill:
                        type: string
                      time_stamp:
                        type: string
                  experience:
                    type: array
                    items:
                      type: object
                    properties:
                      title:
                        type: string
                      company:
                        type: string
                      start_date:
                        type: string
                      end_date:
                        type: string
                      description:
                        type: string

        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request / Data missing"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Username already exists"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"
  /comments/${post_id}:
    get:
      tags:
        - comments
      summary: Get all comments for a post
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    user_id:
                      type: string
                    post_id:
                      type: string
                    content:
                      type: string
                    time_stamp:
                      type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      tags:
        - comments
      summary: Create a new comment
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "This is a comment"
      responses:
        "201":
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comments"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string






components:
  schemas:
    posts:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        content:
          type: string
        user_id:
          type: string
        time_stamp:
          type: string
    user:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        image:
          type: string
        headline:
          type: string
        summary:
          type: string
        password:
          type: string
        email:
          type: string
        education:
          type: array
          items:
            type: object
          properties:
            school:
              type: string
            degree:
              type: string
            field_of_study:
              type: string
            start_date:
              type: string
            end_date:
              type: string
            description:
              type: string
        skill:
          type: array
          items:
            type: object
          properties:
            skill:
              type: string
            time_stamp:
              type: string
        experience:
          type: array
          items:
            type: object
          properties:
            title:
              type: string
            company:
              type: string
            start_date:
              type: string
            end_date:
              type: string
            description:
              type: string
    reactions:
      type: object
      properties:
        _id:
          type: string
        user_id:
          type: string
        post_id:
          type: string
        comment_id:
          type: string
        reaction:
          type: string
          enum:
            - like
            - love
            - haha
            - wow
            - sad
            - angry
        time_stamp:
          type: string
    comments:
      type: object
      properties:
        _id:
          type: string
        user_id:
          type: string
        post_id:
          type: string
        comment_id:
          type: string
        content:
          type: string
        time_stamp:
          type: string
    connections:
      type: object
      properties:
        _id:
          type: string
        user_id:
          type: array
          items:
            type: string
        time_stamp:
          type: string








